<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Sample</name>
  <uuid>512b32e0-a82b-4acd-b349-72972ff02764</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Input is "Hello" 
then
	set decision to "Vivek" ;
else
	set decision to "Satwal" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
